version: "3"

services:
  app:
    build:
      context: app
    ports:
      - "5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/items
    depends_on:
      - postgres   

  nginx:
    image: nginx:latest
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
      - "80:80"

  postgres:
    container_name: postgres
    image: postgres:12
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=items
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata: {}
